/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PdfMermaidFixPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var DEFAULT_SETTINGS = {
  pythonScriptPath: ""
};
var PdfMermaidFixPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MdExportSettingTab(this.app, this));
    this.addCommand({
      id: "export-to-word",
      name: "Export active file to Word",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView && markdownView.file) {
          if (!checking) {
            void this.exportToWord(markdownView.file);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "export-to-pdf",
      name: "Export active file to PDF (Direct Engine)",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView && markdownView.file) {
          if (!checking) {
            void this.exportToPdf(markdownView.file);
          }
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Export to Word").setIcon("document").onClick(() => {
              void this.exportToWord(file);
            });
          });
          menu.addItem((item) => {
            item.setTitle("Export to PDF (Direct Engine)").setIcon("pdf-file").onClick(() => {
              void this.exportToPdf(file);
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu) => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (activeView && activeView.file) {
          menu.addItem((item) => {
            item.setTitle("Export to Word").setIcon("document").onClick(() => {
              if (activeView.file) {
                void this.exportToWord(activeView.file);
              }
            });
          });
          menu.addItem((item) => {
            item.setTitle("Export to PDF (Direct Engine)").setIcon("pdf-file").onClick(() => {
              if (activeView.file) {
                void this.exportToPdf(activeView.file);
              }
            });
          });
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async exportToPdf(file) {
    new import_obsidian.Notice("Starting High-Quality PDF export...");
    try {
      const adapter = this.app.vault.adapter;
      if (!(adapter instanceof import_obsidian.FileSystemAdapter)) {
        new import_obsidian.Notice("Error: Cannot determine vault absolute path.");
        return;
      }
      const basePath = adapter.getBasePath();
      const absoluteInputPath = path.join(basePath, file.path);
      const absoluteOutputPath = absoluteInputPath.replace(/\.md$/, ".pdf");
      const pluginDir = path.join(basePath, this.app.vault.configDir, "plugins", this.manifest.id);
      const scriptPath = path.join(pluginDir, "render_pdf.js");
      const nodePaths = ["/opt/homebrew/bin/node", "/usr/local/bin/node", "node"];
      const tryRun = (index) => {
        if (index >= nodePaths.length) {
          new import_obsidian.Notice("PDF export failed. Node runtime not found.");
          return;
        }
        const nodeBin = nodePaths[index];
        const cmd = `"${nodeBin}" "${scriptPath}" "${absoluteInputPath}" "${absoluteOutputPath}"`;
        (0, import_child_process.exec)(cmd, (error, stdout, stderr) => {
          if (error) {
            if (error.code === 127 || error.message.includes("not found") || error.message.includes("ENOENT")) {
              tryRun(index + 1);
              return;
            }
            console.error(`PDF export error: ${error.message}
${stderr}`);
            new import_obsidian.Notice(`PDF export failed: ${error.message}`);
            return;
          }
          new import_obsidian.Notice("PDF export complete! Saved as: " + file.path.replace(/\.md$/, ".pdf"));
        });
      };
      tryRun(0);
    } catch (error) {
      const err = error;
      console.error("Failed to export PDF:", err);
      new import_obsidian.Notice(`Failed to export PDF: ${err.message}`);
    }
  }
  async exportToWord(file) {
    new import_obsidian.Notice("Starting Word export via Python script...");
    try {
      const adapter = this.app.vault.adapter;
      if (!(adapter instanceof import_obsidian.FileSystemAdapter)) {
        new import_obsidian.Notice("Error: Cannot determine vault absolute path.");
        return;
      }
      const basePath = adapter.getBasePath();
      const absoluteInputPath = path.join(basePath, file.path);
      const absoluteOutputPath = absoluteInputPath.replace(/\.md$/, ".docx");
      const pluginDir = path.join(basePath, this.app.vault.configDir, "plugins", this.manifest.id);
      const bundledScriptPath = path.join(pluginDir, "md_to_docx.py");
      const scriptPath = this.settings.pythonScriptPath || bundledScriptPath;
      const pythonPaths = ["/opt/homebrew/bin/python3", "/usr/local/bin/python3", "python3"];
      const tryRun = (index) => {
        if (index >= pythonPaths.length) {
          new import_obsidian.Notice("Word export failed. Python3 not found in standard paths.");
          return;
        }
        const py = pythonPaths[index];
        const cmd = `"${py}" "${scriptPath}" "${absoluteInputPath}" -o "${absoluteOutputPath}"`;
        (0, import_child_process.exec)(cmd, (error, stdout, stderr) => {
          if (error) {
            console.error(`exec error with ${py}: ${error.message}`);
            if (error.code === 127 || error.message.includes("not found") || error.message.includes("ENOENT")) {
              tryRun(index + 1);
              return;
            }
            const fullErr = error.message + "\n" + (stderr || "");
            if (fullErr.includes("No module named 'docx'")) {
              new import_obsidian.Notice('Word export failed: Missing Python package "python-docx". Please run "pip install python-docx Pillow" in terminal.', 1e4);
            } else if (fullErr.includes("No module named 'PIL'") || fullErr.includes("No module named 'Pillow'")) {
              new import_obsidian.Notice('Word export failed: Missing Python package "Pillow". Please run "pip install python-docx Pillow" in terminal.', 1e4);
            } else {
              new import_obsidian.Notice(`Word export failed: ${error.message}`);
            }
            return;
          }
          if (stderr) {
            console.warn(`stderr: ${stderr}`);
          }
          new import_obsidian.Notice("Word export complete! Saved as: " + file.path.replace(/\.md$/, ".docx"));
        });
      };
      tryRun(0);
    } catch (error) {
      const err = error;
      console.error(err);
      new import_obsidian.Notice(`An error occurred while preparing Word export: ${err.message}`);
    }
  }
};
var MdExportSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Python script path").setDesc("Absolute path to your md_to_docx.py script (Leave empty to use the built-in bundled script).").addText((text) => text.setPlaceholder("Leave empty to use default bundled script").setValue(this.plugin.settings.pythonScriptPath).onChange(async (value) => {
      this.plugin.settings.pythonScriptPath = value;
      await this.plugin.saveSettings();
    }));
  }
};
