/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PdfMermaidFixPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var DEFAULT_SETTINGS = {
  pythonScriptPath: ""
};
var PdfMermaidFixPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MdExportSettingTab(this.app, this));
    this.addCommand({
      id: "export-to-word",
      name: "Export active file to Word",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView && markdownView.file) {
          if (!checking) {
            this.exportToWord(markdownView.file);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "export-to-pdf-mermaid-fix",
      name: "Export active file to PDF (Mermaid Fix)",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView && markdownView.file) {
          if (!checking) {
            this.exportToPdf(markdownView.file);
          }
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Export to Word").setIcon("document").onClick(() => this.exportToWord(file));
          });
          menu.addItem((item) => {
            item.setTitle("Export to PDF (Mermaid Fix)").setIcon("pdf-file").onClick(() => this.exportToPdf(file));
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (view && view.file) {
          const file = view.file;
          menu.addItem((item) => {
            item.setTitle("Export to Word").setIcon("document").onClick(() => this.exportToWord(file));
          });
          menu.addItem((item) => {
            item.setTitle("Export to PDF (Mermaid Fix)").setIcon("pdf-file").onClick(() => this.exportToPdf(file));
          });
        }
      })
    );
  }
  onunload() {
    const styleEl = document.getElementById("mermaid-pdf-fix");
    if (styleEl) {
      styleEl.remove();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async exportToPdf(file) {
    new import_obsidian.Notice("Applying Mermaid PDF Fix and opening native export...");
    try {
      let styleEl = document.getElementById("mermaid-pdf-fix");
      if (!styleEl) {
        styleEl = document.createElement("style");
        styleEl.id = "mermaid-pdf-fix";
        styleEl.textContent = `
				@media print {
					.mermaid svg {
						max-width: 100% !important;
						height: auto !important;
						page-break-inside: avoid;
					}
				}
				`;
        document.head.appendChild(styleEl);
      }
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView && activeView.file === file) {
        this.app.commands.executeCommandById("workspace:export-pdf");
      } else {
        new import_obsidian.Notice("Please open the file to export it to PDF.");
      }
    } catch (error) {
      console.error(error);
      new import_obsidian.Notice("Failed to trigger PDF export");
    }
  }
  async exportToWord(file) {
    if (!this.settings.pythonScriptPath) {
      new import_obsidian.Notice("Please configure the Python script path in settings first.");
      return;
    }
    new import_obsidian.Notice("Starting Word export via Python script...");
    try {
      const adapter = this.app.vault.adapter;
      if (!adapter.getBasePath) {
        new import_obsidian.Notice("Error: Cannot determine vault absolute path.");
        return;
      }
      const basePath = adapter.getBasePath();
      const absoluteInputPath = path.join(basePath, file.path);
      const absoluteOutputPath = absoluteInputPath.replace(/\.md$/, ".docx");
      const scriptPath = this.settings.pythonScriptPath;
      const cmd = `python3 "${scriptPath}" "${absoluteInputPath}" -o "${absoluteOutputPath}"`;
      (0, import_child_process.exec)(cmd, (error, stdout, stderr) => {
        if (error) {
          console.error(`exec error: ${error}`);
          new import_obsidian.Notice("Word export failed. Check console for details.");
          return;
        }
        if (stderr) {
          console.warn(`stderr: ${stderr}`);
        }
        new import_obsidian.Notice("Word export complete! Saved as: " + file.path.replace(/\.md$/, ".docx"));
      });
    } catch (error) {
      console.error(error);
      new import_obsidian.Notice("An error occurred while preparing Word export.");
    }
  }
};
var MdExportSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Python script path").setDesc("Absolute path to your md_to_docx.py script (Required for Word export).").addText((text) => text.setPlaceholder("/path/to/md_to_docx.py").setValue(this.plugin.settings.pythonScriptPath).onChange(async (value) => {
      this.plugin.settings.pythonScriptPath = value;
      await this.plugin.saveSettings();
    }));
  }
};
